# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
